resources:
  - name: my-git-repo
    type: git
    source:
      uri: https://github.com/UmamaheshMaxwell/my-concourse-app.git
      branch: master

  - name: my-trigger
    type: time
    source:
      interval: 2m
jobs:
- name: first-job
  public: true
  serial: true
  plan:
  - get: my-git-repo
  - get: my-trigger
    trigger: true
  - task: my-first-task
    file: my-git-repo/ci/tasks/inputs_required.yml



