resources:
  - name: my-git-repo
    type: git
    source:
      uri: https://github.com/UmamaheshMaxwell/my-concourse-app.git
      branch: master
jobs:
 - name: first-job
   public: true
   plan:
    - get: my-git-repo
    - task: my-first-task
      file: my-git-repo/ci/tasks/inputs_required.yml