resources:
  - name: my-git-repo
    type: git
    source:
      uri: https://github.com/UmamaheshMaxwell/my-concourse-app.git
      branch: master

jobs:
- name: first-job
  public: true
  serial: true
  plan:
  - get: my-git-repo
  - task: my-first-task
    config:
      platform: linux

      image_resource:
       type: docker-image
       source: {repository: busybox}

      inputs:
      - name: my-git-repo
        path: my-git-repo

      run:
        path: sh
        args:
        - -c
        - |
          sh my-git-repo/simple-task.sh ((aws_access_key_id)) ((aws_secret_access_key))

      # run:
      #   path: sh
      #   args: [my-git-repo/simple-task.sh ((aws_access_key_id))]
  



