resources:
  - name: my-git-repo
    type: git
    source:
      uri: https://github.com/UmamaheshMaxwell/my-concourse-app.git
      branch: master
jobs:
 - name: first-job
   public: true
   plan:
    - get: my-git-repo
    - task: my-first-task
      config: 
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: busybox}
        run:
          path: echo
          args:
           - hello world